### ISSUE TITLE
 Unable to load URL: http://127.0.0.1:XXXXX

### ISSUE THREAD

**Issue by thbar** [oesmith/puffing-billy#23]
I'm a newcomer to puffing-billy so bear with me! I suspect there's something obvious there, but cannot find a way to make this work.

I attempted to enable puffing-billy on a capybara-webkit-enabled rspec feature. Note that I had to revert to an older RSpec version (see #19) to get that far.

As soon as I run the following spec (extract):

``` ruby
require 'spec_helper'

feature 'Sign-up' do
  scenario 'as a regular user', focus: true, js: true, driver: :webkit_billy do
    visit '/'
    # ...
  end
end
```

I get the following stack trace:

```
Failure/Error: visit '/'
     Capybara::Webkit::InvalidResponseError:
       Unable to load URL: http://127.0.0.1:58597/ because of error loading http://127.0.0.1:58597/: Connection refused
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/capybara-webkit-0.14.2/lib/capybara/webkit/browser.rb:205:in `check'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/capybara-webkit-0.14.2/lib/capybara/webkit/browser.rb:142:in `command'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/capybara-webkit-0.14.2/lib/capybara/webkit/browser.rb:18:in `visit'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/capybara-webkit-0.14.2/lib/capybara/webkit/driver.rb:29:in `visit'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/capybara-2.0.3/lib/capybara/session.rb:183:in `visit'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/capybara-2.0.3/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/sign_up_spec.rb:9:in `block (2 levels) in <top (required)>'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:113:in `instance_eval'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:113:in `block in run'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:253:in `with_around_each_hooks'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:110:in `run'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:378:in `block in run_examples'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:374:in `map'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:374:in `run_examples'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:360:in `run'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `map'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `block in run'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/reporter.rb:34:in `report'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:25:in `run'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:69:in `run'
     # /Users/thbar/.rvm/gems/ruby-1.9.3-p392-railsexpress@myapp/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:8:in `block in autorun'
```

Is there anyone with an idea here?

Thanks!

**Comment by plicjo** [comment]
I had this same issue with a fully up-to-date webkit version. I had to switch to poltergeist to get Capybara to work on the CI server.

I believe the issues lies somewhere in the **poltergeist-billy** driver.
