### ISSUE TITLE
eventmachine not initialized - proxy isn't working

### ISSUE THREAD

**Issue by knagode** [oesmith/puffing-billy#253]
I am getting this error
```
An error occurred in an `after(:suite)` hook.
Failure/Error: Socket.unpack_sockaddr_in(EM.get_sockname(@signature)).first

RuntimeError:
  eventmachine not initialized: evma_get_sockname
```

Anyone has idea why? 

My setup in rails_spec.rb:

```
Capybara.register_driver :chrome do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_argument('--lang=de')
  options.add_argument('--verbose')
  options.add_argument("--proxy-server=#{Billy.proxy.host}:#{Billy.proxy.port}")

  Capybara::Selenium::Driver.new(
    app,
    browser: :chrome,
    #profile: profile
    options: options
  )
end

Capybara.javascript_driver = :chrome 
```

**Comment by ronwsmith** [comment]
@knagode can you try running on the branch in this PR and see if it works?  https://github.com/oesmith/puffing-billy/pull/251

**Comment by knagode** [comment]
@knagode I tried but it didn't help. Other ideas maybe?

**Comment by knagode** [comment]
I tried to install it in clean project on same machine and it worked.. Apparently there is a conflict with another gem/configuration. Will write here when I figure it out.

**Comment by knagode** [comment]
I found that problem is happening due to webmock which we heavily use. I think that both gems are super useful and they should work together. 

Example controller method: 
```
  def test_page
    data = HTTParty.get('http://yahoo.com/data.json', format: :json)
    render html: ('<html><body><b>Data=' + data.to_json + '</b> <script src="http://google.com/script.js"></script></body></html>').html_safe
  end
```

Is there no way to make those two gems work together?

**Comment by ronwsmith** [comment]
In this example, what do you expect WebMock to do and what do you expect PuffingBilly to do?

**Comment by knagode** [comment]
@ronwsmith I was slowly removing gems from my repo and managed to fix `eventmachine not initialized: evma_get_sockname`. 

In my case problem was: `gem fake_stripe`. Anyway I wasn't able to use Puffing Billy because it doesnt allow me to use WebMock & Chrome proxy together. Why is this not possible? Do you see that this gem would be really powerful if it would allow co-existance of both as they are both super important gems ... Do you know why exactly do they not work together? What should be changed in order to use both?

**Comment by ronwsmith** [comment]
Puffing-billy is a proxy itself.  If you use it as the proxy in Chrome, it will work just fine.  Not sure what other proxy settings you're using in Chrome or why, but as far as I know you can only use one proxy in any browser.

**Comment by knagode** [comment]
Sure. PuffingBilly is **proxy for browser based requests**. 

But if you are building app which is also making requests to external servers (e.g. requests to Stripe, Facebook Graph, etc ...) you sooner or later need something for stubbing those requests. That is why we use [WebMock](https://github.com/bblimke/webmock).

I would expect that those 2 gems would work together because they are solving 2 problems. [ I saw that I am not the only one who expected that this would work out of the box. ](https://github.com/oesmith/puffing-billy/issues/44)

**Comment by ronwsmith** [comment]
Have you tried the suggestions in that linked issue?  Happy to accept a PR with README changes that document it better.

**Comment by ronwsmith** [comment]
Just updated eventmachine in 1.1.3.  Please try it out and see if this issue persists.

**Comment by fukayatsu** [comment]
This issue persists on puffing-billy v1.1.3 with knapsack_pro queue mode.

```
An error occurred in an `after(:suite)` hook.
--
  | Failure/Error: Socket.unpack_sockaddr_in(EM.get_sockname(@signature)).first
  |  
  | RuntimeError:
  | eventmachine not initialized: evma_get_sockname
  | # /bundle/gems/puffing-billy-1.1.3/lib/billy/proxy.rb:43:in `get_sockname'
  | # /bundle/gems/puffing-billy-1.1.3/lib/billy/proxy.rb:43:in `port'
  | # /bundle/gems/puffing-billy-1.1.3/lib/billy/proxy.rb:29:in `stop'
  | # /bundle/gems/puffing-billy-1.1.3/lib/billy/init/rspec.rb:17:in `block (2 levels) in <top (required)>'
  | # /bundle/gems/knapsack_pro-1.2.0/lib/knapsack_pro/runners/queue/rspec_runner.rb:81:in `run_tests'
  | # /bundle/gems/knapsack_pro-1.2.0/lib/knapsack_pro/runners/queue/rspec_runner.rb:34:in `run'
  | # /bundle/gems/knapsack_pro-1.2.0/lib/tasks/queue/rspec.rake:6:in `block (3 levels) in <top (required)>'
```

**Comment by ronwsmith** [comment]
@AlanFoster can you take a look at this issue?  Seems to be introduced by your PR https://github.com/oesmith/puffing-billy/pull/239 .  Thanks!

**Comment by julioolvr** [comment]
I don't want to add much noise, but we've been looking into an issue similar to this one today. Seems like eventmachine's reactor is a singleton, right? So other gems that use it could theoretically stop it before `puffing-billy` does? We'll work around this for now by adding a check for `EM.reactor_running?` before `Billy::Proxy#stop` and see how that goes, so just sharing in case it makes sense to add this to `puffing-billy`.

**Comment by ronwsmith** [comment]
@knagode is this still an issue for you?

@julioolvr how did that workaround work?  If it works, can you submit a PR with it?  Thanks!

**Comment by julioolvr** [comment]
We haven’t had issues in a while to the point I had completely forgot about this, so I guess the workaround was a success. I’ll see if I have time to send a PR during the week, but in the meantime this is the whole code for the patch (we have it in our `rails_helper.rb` file)

```rb
# Patch `puffing-billy`'s proxy so that it doesn't try to stop
# eventmachine's reactor if it's not running.
module BillyProxyPatch
  def stop
    return unless EM.reactor_running?

    super
  end
end

Billy::Proxy.prepend(BillyProxyPatch)
```

**Comment by julioolvr** [comment]
I looked a bit into opening a PR but I'm not sure how I'd write a test for it. Additionally, I had some issues `bundle install`ing on macOS (when trying to compile `capybara-webkit`, apparently) and I wasn't able to build an image out of the provided `Dockerfile`. In any case, the change would literally be adding that guard clause with `EM.reactor_running?`, in case someone with the project already up and running wants to give it a try.

**Comment by thbar** [comment]
@julioolvr thanks for your patch, which apparently removes the error in my case too.

**Comment by ArturT** [comment]
@fukayatsu You asked about the case when puffing-billy gem fails when using [knapsack_pro](https://github.com/KnapsackPro/knapsack_pro-ruby) gem in [Queue Mode](https://youtu.be/hUEB1XDKEFY) to run your tests in parallel on CI server. I got patch fix from one of users that was helpful:

```ruby
# rails_helper.rb or spec_helper.rb

# A patch to `puffing-billy`'s proxy so that it doesn't try to stop
# eventmachine's reactor if it's not running.
module BillyProxyPatch
  def stop
    return unless EM.reactor_running?
    super
  end
end
Billy::Proxy.prepend(BillyProxyPatch)

# A patch to `puffing-billy` to start EM if it has been stopped
Billy.module_eval do
  def self.proxy
    if @billy_proxy.nil? || !(EventMachine.reactor_running? && EventMachine.reactor_thread.alive?)
      proxy = Billy::Proxy.new
      proxy.start
      @billy_proxy = proxy
    else
      @billy_proxy
    end
  end
end

if ENV["KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC"]
  KnapsackPro::Hooks::Queue.before_queue do
    # executes before Queue Mode starts work
    Billy.proxy.start
  end

  KnapsackPro::Hooks::Queue.after_queue do
    # executes after Queue Mode finishes work
    Billy.proxy.stop
  end
end
```

I've updated FAQ in my docs https://github.com/KnapsackPro/knapsack_pro-ruby#how-to-configure-puffing-billy-gem-with-knapsack-pro-queue-mode

**Comment by ronwsmith** [comment]
Happy to accept a PR with that patch (and tests) if someone wants to put one up.

**Comment by dlozano** [comment]
I am also having the this issue when I switch to unicorn as Capybara rack server. In addition to @ArturT patch I needed to patch `port_in_use?`

I use both puffing-billy and webmock

```ruby
module BillyProxyPatch
  def stop
    return unless EM.reactor_running?
    super
  end

  def port_in_use?(port)
    return unless EM.reactor_running?
    super
  end
end
```

**Comment by senid231** [comment]
I have a similar problem but none of above fixes didn't work for me

following works for me
```ruby
module BillyProxyPatch
  protected

  def port_in_use?(port)
    Timeout::timeout(1) do
      s = TCPSocket.new(host, port)
      s.close
      Billy.log(:info, "puffing-billy: Waiting for event machine to shutdown on port #{port}")
      s
    end
  rescue Errno::ECONNREFUSED, Errno::EADDRNOTAVAIL, Errno::ENETUNREACH, Errno::ECONNRESET, Timeout::Error
    false
  end
end
```

because in my case `TCPSocket#new` hangs for 60 seconds (then timeout in `wait_for_server_shutdown` being called)

PS `TCPSocket#new` has a `connection_timeout` option, but we use `socksify` as a dependency of one of our gems which monkey patch TCPSocket and removes this option.

**Comment by dan-jensen** [comment]
For those encountering this exception intermittently: For me WebMock is [occasionally unable to find registered stubs](https://github.com/bblimke/webmock/issues/1100) and raises `WebMock::NetConnectNotAllowedError`.

If WebMock raises an exception, then eventmachine stops and any attempts to call the proxy result in "eventmachine not initialized: evma_get_sockname". So if you're encountering this evma_get_sockname exception, and monkey-patching `stop` doesn't solve the problem, check to make sure there are no earlier exceptions killing your eventmachine.
